services:
  - type: web
    name: reachinbox-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: WORKER_CONCURRENCY
        value: 5
      - key: WORKER_RATE_LIMIT_MAX
        value: 10
      - key: WORKER_RATE_LIMIT_DURATION_MS
        value: 2000
      - key: MAX_EMAILS_PER_HOUR
        value: 200
      - key: MAX_EMAILS_PER_HOUR_PER_SENDER
        value: 50
